name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Initialise docs
        run: |
          pip install mkdocs
          mkdocs new .
          mkdocs build

      - name: Convert ipynb to md
        run: |
          pip install nbconvert
          jupyter nbconvert --to markdown aoc2019/solutions.ipynb

      - name: Move pages
        run: |
          mv real_mkdocs.yml mkdocs.yml
          mv aoc2019/solutions.md docs/solutions.md

      - name: Deploy
        run: mkdocs gh-deploy
