name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build and deploy docs
        run: |
          pip install mkdocs
          mkdocs new .
          mkdocs build
          mkdocs gh-deploy
